### ISSUE TITLE
Feature request: abilty to invert intervals

### ISSUE THREAD

**Issue by art-of-dom** [pedrozath/coltrane#13]
Coltrane should be able to invert intervals which is a very basic and useful operation for manipulating intervals. 

For example, if I created an interval of a Perfect Fifth Coltrane should have a way to invert the original interval to a Perfect Fourth.

**Comment by pedrozath** [comment]
This functionality exists:

```ruby
(-Interval.perfect_fifth).full_name
=> "Perfect Fourth"
```

I'll add it to the wiki. Thanks for pointing out!

**Comment by pedrozath** [comment]
It's actually already on the wiki
