### ISSUE TITLE
Output sharps/flats based on the key

### ISSUE THREAD

**Issue by turboladen** [pedrozath/coltrane#3]
Super cool app (found it via your reddit post)! I was just reading through the README and saw that one of the `Fm7` examples that, for example, `D#` is in the scale; generally, unless in some larger context, F minor is expressed in terms of flats (Ab, Bb, Db, Eb) instead of their sharp counterparts. It'd be nice to have coltrane express them accordingly. 

tl;dr It just feels a little awkward to me to see "D#" in a spot where I'd expect "Eb"; makes me pause a sec and double-check what I'm looking at.

**Comment by pedrozath** [comment]
Hey thanks! 🙏🏻

So I won’t say I was totally unaware about the fact there’s a convention for when to use sharps or flats. But the logic of whether to use one or the other still scapes from my knowledge.

But we definitely have to fix that. I’m positive there must be a way choose which note to show regardless if they are the same pitch. Even if we hardcode at some point.

Could you share me some knowledge on whether do we use sharps or flats? How does that work?

Could you t

**Comment by pedrozath** [comment]
(Please ignore my stupid typing mistakes as I’m typing on a moving train right now)

**Comment by turboladen** [comment]
> How does that work?

Generally, it's based off the key/scale you're talking about--some keys are always denoted in flats, others in sharps. I forget the exact rule, but I think the general rule of thumb is that you use the whichever (flats vs sharps) that would result in the reader having to read the least amount of those marks. Further, when writing something that uses flats to denote its key, on a staff you always notate the flats in the following order: B, E, A, D, G, C, F; when writing in a key that uses sharps, you always notate them in order: F, C, G, D, A, E, B.

For example, [F# major](https://en.wikipedia.org/wiki/F-sharp_major) and [Gb major](https://en.wikipedia.org/wiki/G-flat_major) get you playing the same notes, but some may prefer one of the other when notating or playing.

So maybe in code you could make some association to a key (ex C major) to an object that captures the flats/sharps associated with it, then if you see sharps, you can display accordingly? I have to run now, but maybe I peek at the code later.

**Comment by pedrozath** [comment]
Solved by 687200b43d88a72dd4b779d561f7d0784f42bc25
