### ISSUE TITLE
Output natural symbols only when relevant

### ISSUE THREAD

**Issue by turboladen** [pedrozath/coltrane#4]
This is another issue of preference. At least in my experience, you usually only see natural symbols in music when the context that you're in says that you should be playing a flat or sharp. Seeing them in, say, the [D major scale example](https://github.com/pedrozath/coltrane/blob/master/img/screen-8.png) makes me pause and double-check the context I'm in: "hmmm... I see G♮--did I actually ask for the right thing?".

Seems like the UI would be less cluttered and it'd be a little more natural to only include the natural symbols when they mean to do something out of the scale's normal mode: like if the user wanted to see "f harmonic minor", you'd show an E♮ instead of E♭.

Again, just some thoughts I figured I throw out there.

**Comment by pedrozath** [comment]
I find your point really relevant.

The reason I added the natural symbols was to give them the same sense of visual weight of flat and sharp notes.

When I was building, that's the options I had:
<img width="675" alt="screen shot 2018-01-30 at 21 43 36" src="https://user-images.githubusercontent.com/913275/35598450-992ffc18-060a-11e8-919a-7da675b0ee09.png">
<img width="666" alt="screen shot 2018-01-30 at 21 42 50" src="https://user-images.githubusercontent.com/913275/35598451-99598a7e-060a-11e8-91d2-39e76e66b2ad.png">
<img width="680" alt="screen shot 2018-01-30 at 21 39 28" src="https://user-images.githubusercontent.com/913275/35598452-997cc9a8-060a-11e8-9985-f44ff6b68c5d.png">
<img width="659" alt="screen shot 2018-01-30 at 21 38 13" src="https://user-images.githubusercontent.com/913275/35598454-99a163a8-060a-11e8-9095-5304ee2cbfb8.png">

And the final version:
<img width="668" alt="screen shot 2018-01-30 at 22 11 13" src="https://user-images.githubusercontent.com/913275/35598449-99081842-060a-11e8-8120-cbc60a96ea0b.png">

So if you had to choose, which one would you pick?

**Comment by turboladen** [comment]
> to give them the same sense of visual weight of flat and sharp notes.

Ah yeah, that makes sense. I can't really speak to UX/UI stuff since I suck there, but if I'm using this app for making/writing/learning music, I personally think the former (the one without the natural symbol) reads in a more familiar manner; it feels more like I'm reading a piece of sheet music.

**Comment by pedrozath** [comment]
#fixed
