### ISSUE TITLE
"Gem.gunzip is deprecated; use Gem::Util.gunzip instead." when using Coltrane

### ISSUE THREAD

**Issue by naltun** [pedrozath/coltrane#40]
I am using `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]` and Gem `v2.7.7`.
I found [this](https://github.com/ruby/ruby/commit/c6da9cadb346cc1d250c7ed6d8fd33c62a11030e) link referring to deprecating Gem `v2.7.6`. I'm not sure if this issue comes from my installation or Coltrane?

![image](https://user-images.githubusercontent.com/7507990/42095030-7fe27c0a-7b7f-11e8-9b37-bad66b98b17a.png)

**Comment by pedrozath** [comment]
I think this is related to your build. Is it still happening?

**Comment by naltun** [comment]
It is. I am using Gem v2.7.7.

Is one of your files calling `Gem.unzip`? [This issue](https://github.com/misogi/vscode-ruby-rubocop/issues/77) says that `Gem::Util.gunzip` is the future method to be used. Not sure if this is on my side, or if it's being called in the code.
