### ISSUE TITLE
coltrane ... --on guitar: Strings depicted in unconventional (reverse) order

### ISSUE THREAD

**Issue by bwagner** [pedrozath/coltrane#41]
`coltrane scale F pentatonic --on guitar`

 Strings are depicted in unconventional order: **topmost** in `coltrane`'s representation is the **low** E string:
```
E  | -- -- G  -- A  -- B  -- -- D  -- E  -- -- G  -- A  -- B  -- -- D  --
A  | -- B  -- -- D  -- E  -- -- G  -- A  -- B  -- -- D  -- E  -- -- G  --
D  | -- E  -- -- G  -- A  -- B  -- -- D  -- E  -- -- G  -- A  -- B  -- --
G  | -- A  -- B  -- -- D  -- E  -- -- G  -- A  -- B  -- -- D  -- E  -- --
B  | -- -- D  -- E  -- -- G  -- A  -- B  -- -- D  -- E  -- -- G  -- A  --
E  | -- -- G  -- A  -- B  -- -- D  -- E  -- -- G  -- A  -- B  -- -- D  --
```
Compare this to the representations found via: [google image search](https://www.google.ch/search?q=fretboard&tbm=isch), where **topmost** is the **high** E string.

**Comment by pedrozath** [comment]
Good catch. Thanks @bwagner. Could you install the newest version and test for me if its fine?

**Comment by bwagner** [comment]
Awesome, thank you @pedrozath !
