### ISSUE TITLE
Abnormal end

### ISSUE THREAD

**Issue by Mrucznik** [pedrozath/coltrane#56]
Hello,
When using CLI parameters, I got an "Abnormal end" message.

To reproduce:
```sh
$ docker run -it --entrypoint /bin/bash ruby
$ gem install coltrane
$ coltrane chords CM7 --on guitar
This terminal doesn't seem to support true color. Try something like iTerm2 (for macOS), VTE or Konsole (for linux) or Hyper (for Windows) and you'll see the true magic!

-> coltrane chords CM7 --on guitar 

Abnormal end
```

**Comment by stefj02** [comment]
Same for WSL, anyone knows how to fix this?

**Comment by kit-finknottle** [comment]
I am also getting "Abnormal end" and I am using iTerm2 as suggested.

```
MacBook-Air ~ % coltrane chords --notes C-E-G

-> coltrane chords --notes C-E-G

Abnormal end
```

**Comment by follower** [comment]
Couple of pointers (based on some brief searches) in case it's useful to anyone trying to investigate this error further:

 * It appears the origin of the specific "Abnormal end" message is this code: https://github.com/pedrozath/gambiarra/blob/93bf6b5f560b9d31c337f759a86d1f9332c08c15/lib/gambiarra/history.rb#L25-L29

 * As I understand it (not being a Ruby developer), based on the traceback shown in https://github.com/pedrozath/coltrane/issues/62 it appears the program flow sequence includes these sections of code:
   * https://github.com/pedrozath/coltrane/blob/c05d407962470ed2eb7894012f02fed76a25a106/exe/coltrane#L24
   * https://github.com/pedrozath/gambiarra/blob/93bf6b5f560b9d31c337f759a86d1f9332c08c15/lib/gambiarra/app.rb#L15-L27

* Also relevant is that the core functionality seems to be implemented as a library & given the error seems like it _could_ be bundling/packaging related someone, might have more like luck just accessing the library directly.

  The wiki has what at first glance looks like reasonable documentation for the library: https://github.com/pedrozath/coltrane/wiki/Core-music-theory-library

**Comment by pedrozath** [comment]
The issue here is that the command syntax has changed but I forgot to update the Readme.

Just updated the examples above but some other must be outdated.

When in doubt, just run `coltrane` and select the options interactively. After every interaction it will output the command that you could have typed to get the information directly:

```
-> coltrane show scale tone:F scale:Flamenco representation:Guitar     <<-------- this is the command

E -- | F  F♯ -- -- A  A♯ -- C  C♯ -- D♯ -- F  F♯ -- -- A  A♯ -- C  C♯ -- D♯
B -- | C  C♯ -- D♯ -- F  F♯ -- -- A  A♯ -- C  C♯ -- D♯ -- F  F♯ -- -- A  A♯
G -- | -- A  A♯ -- C  C♯ -- D♯ -- F  F♯ -- -- A  A♯ -- C  C♯ -- D♯ -- F  F♯
D -- | D♯ -- F  F♯ -- -- A  A♯ -- C  C♯ -- D♯ -- F  F♯ -- -- A  A♯ -- C  C♯
A A  | A♯ -- C  C♯ -- D♯ -- F  F♯ -- -- A  A♯ -- C  C♯ -- D♯ -- F  F♯ -- --
E -- | F  F♯ -- -- A  A♯ -- C  C♯ -- D♯ -- F  F♯ -- -- A  A♯ -- C  C♯ -- D♯

             03    05    07    09       12       15    17    19

? What to do now? (Choose with ↑ ↓ ⏎, filter with 'f')
> 1. Different tone
  2. Different scale
  3. Different representation
  4. Go back
```

**Comment by Mrucznik** [comment]
Oh,
`coltrane show chord chord:CM7 chord_representation:GuitarChordChart`
works, thanks!
