### ISSUE TITLE
Commands not recognized

### ISSUE THREAD

**Issue by kronmj** [pedrozath/coltrane#58]
Recently I've installed coltrane and have been trying to get ruby to recognize 
While the Core Music Theory library works with irb, the main CLI doesn't recognize any of the coltrane commands.

Here's an example of what I get when I input a command in irb
```
irb(main):005:0> coltrane chords --notes C-E-G
/usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/irb/workspace.rb:119:in `eval': (irb):5: syntax error, unexpected constant, expecting `do' or '{' or '(' (SyntaxError)
coltrane chords --notes C-E-G
                        ^
from /usr/local/Cellar/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
from /usr/local/opt/ruby/bin/irb:25:in `load'
from /usr/local/opt/ruby/bin/irb:25:in `<main>'
```
Outside of irb, I get the `coltrane: command not found` statement.
I'm using coltrane 4.1.1 and ruby 3.1.2p20

**Comment by pedrozath** [comment]
The Readme had old syntax.

Try running just `coltrane` and navigate interactively. Before every result output, there is a line containing the exact command you could have ran to get there directly.
