### ISSUE TITLE
abnormal end

### ISSUE THREAD

**Issue by OrionRandD** [pedrozath/coltrane#67]
I also run in "abnormal end" error when running it on Linux (debian)
Is this project still maintained?
:(

**Comment by pedrozath** [comment]
Yes, the project is actively maintained. 

Could you please describe which command you were running?

**Comment by OrionRandD** [comment]
> Yes, the project is actively maintained.
> 
> Could you please describe which command you were running?

 coltrane C-A-D
This terminal doesn't seem to support true color. Try something like iTerm2 (for macOS), VTE or Konsole (for linux) or Hyper (for
Windows) and you'll see the true magic!

-> coltrane C-A-D

Abnormal end

**Comment by OrionRandD** [comment]
Coltrane notes:c-a-d 
Gives me some prompts, but the terminal shows some gibberishes,
I tried with konsole, then chose, e.g. ukelele, and then it exploded...
coltrane notes:c-a-d
? Welcome to Coltrane 4.1.1 (Choose with ↑ ↓ ⏎, filter with 'f')
> 1. notes
  2. chords
  3. scales
  4. progressions
  5. exit

coltrane notes:c-a-d
? Welcome to Coltrane 4.1.1 (You chose: chords)
? What do you need (You chose: show chord)
? Which chord?                                                                                                                                                                            
[0;94m> [0m[33m            

coltrane notes:c-a-d
? Welcome to Coltrane 4.1.1 (You chose: chords)
? What do you need (You chose: show chord)
? Which chord?                                                                                                                                                                            
[0;94m> [0m[33mc                                                                                                                                                                          
? How do you wanna see it? (You chose: GuitarChordChart)
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/theory/note.rb:29:in `initialize'                                                                                                    
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/theory/note.rb:43:in `new'                                                                                                           
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/theory/note.rb:43:in `[]'                                                                                                            
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/theory/chord.rb:93:in `parse_from_name'                                                                                              
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/theory/chord.rb:22:in `initialize'                                                                                                   
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/commands/get_chords_from_string.rb:6:in `new'                                                                                        
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/commands/get_chords_from_string.rb:6:in `block in run'
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/commands/get_chords_from_string.rb:5:in `map'
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/commands/get_chords_from_string.rb:5:in `run'
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/commands/command.rb:7:in `run'
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/ui/views/show_chord.rb:14:in `render'
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/lib/coltrane/ui/base_view.rb:5:in `render'
/var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/view.rb:34:in `respond'
/var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/route.rb:13:in `respond'
/var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/history.rb:31:in `refresh'
/var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/router.rb:21:in `get'
/var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/app.rb:82:in `flow'
/var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/app.rb:26:in `block in start'
/var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/app.rb:26:in `loop'
/var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/app.rb:26:in `start'
/var/lib/gems/3.1.0/gems/coltrane-4.1.1/exe/coltrane:24:in `<top (required)>'
/usr/local/bin/coltrane:25:in `load'
/usr/local/bin/coltrane:25:in `<main>'
Bad constructor. Wrong argument(s).
/var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/app.rb:26:in `block in start': no implicit conversion of nil into Hash (TypeError)
        from /var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/app.rb:26:in `loop'
        from /var/lib/gems/3.1.0/gems/gambiarra-0.0.5/lib/gambiarra/app.rb:26:in `start'
        from /var/lib/gems/3.1.0/gems/coltrane-4.1.1/exe/coltrane:24:in `<top (required)>'
        from /usr/local/bin/coltrane:25:in `load'
        from /usr/local/bin/coltrane:25:in `<main>'

that's what is happening...
:(

**Comment by pedrozath** [comment]
Thanks for the details. I will fix those abnormal errors until monday.

**Comment by OrionRandD** [comment]
> Thanks for the details. I will fix those abnormal errors until monday.

Thx a lot... But, take your time to rest... It is not that urgent for me...

**Comment by pedrozath** [comment]
Thanks but a lot of people have been reporting this.

fixed by #68
