### ISSUE TITLE
Generate pitch sound harmonic signals for aperture

### ISSUE THREAD

**Issue by Endocipher7** [pedrozath/coltrane#70]
Sound wave harmonic detection

**Comment by Endocipher7** [comment]
I'm trying to find a code structure for the Elemental Code structure of molecular biology rendering in terms of geometric patterns formed by combining complex,
hydro-carbons 
Lipids 
Carbides
& amino acids 

I was considering hexadecimal code but I'm writing a thesis on the bonded structure of contemporary conditioning in containment & need a way to categorize and collect the bonding patterns of complex protein structure & elements structures.?

**Comment by pedrozath** [comment]
I'm sorry but this project is about music theory.
Also, write a better issue explaining what exact do you need.
